### ISSUE TITLE
Compiling error in esp32-mqtt.h

### ISSUE THREAD

**Issue by Bearg97** [GoogleCloudPlatform/google-cloud-iot-arduino#105]
Hey,

I am getting a compile error such as 'converting to 'String' from initializer list would use explicit constructor 'String::String(int, unsigned char)' in line 93 in esp32-mqtt.h file.

`void publishTelemetry(const char* data, int length) `
`{
  mqtt->publishTelemetry(data, length);
}`

I tried a couple of things but I could not figure it out.

**Comment by gguuss** [comment]
Thanks for the report!  I must have introduced an issue in the 1.1.5 release. You may need to include Arduino.h in some platforms.

**Comment by gguuss** [comment]
What OS are you using and which version of the ESP32 SDK?

**Comment by gguuss** [comment]
I'm unable to reproduce the issue, please feel free to add comments [in this issue](https://github.com/GoogleCloudPlatform/google-cloud-iot-arduino/issues/92) / try the suggestions from there.
