### ISSUE TITLE
Prefer using the LTS certificate

### ISSUE THREAD

**Issue by gguuss** [GoogleCloudPlatform/google-cloud-iot-arduino#106]
As the project works now, we're using specific keys from the multiple root CAs provided by Google, we should instead find a smaller, canonical one.

**Comment by gguuss** [comment]
Cert is available at mqtt.2030.ltsapis.goog

**Comment by gguuss** [comment]
primary cert: https://pki.goog/gtsltsr/gtsltsr.crt
backup cert: https://pki.goog/gsr4/GSR4.crt

**Comment by gguuss** [comment]
Update: MKR-1000 / ESP8266 do not like the provided cert.

**Comment by gguuss** [comment]
Update: 1.1.7 adds support for the ESP8266 with LTS cert and domain.

**Comment by koromkorom** [comment]
Hi, I have a quick question on this.

This happened recently and then of course ssl fails.:

"For added security, Google Trust Services may switch between the primary and backup certificates at any time without notice."

What would be the best way of handling this for ESP32 (and probably the others also)?

**Comment by gguuss** [comment]
@koromkorom I'm guessing the best way of handling this would be to check both certificates.  This library is still pretty "experimental" and as far as I'm aware, we're just checking the primary certificate.

**Comment by gguuss** [comment]
Closing issue as we're now using LTS cert and domain.  @koromkorom, I've opened another issue for adding support for the backup cert.
