### ISSUE TITLE
Does this library support all 4 types of certificates or only ES256?

### ISSUE THREAD

**Issue by khawajamechatronics** [GoogleCloudPlatform/google-cloud-iot-arduino#111]
If it does support then what are commands to get hex format certificate to be copied into project.

**Comment by gguuss** [comment]
At present, just ES256.  The instructions are listed in [the README](https://github.com/GoogleCloudPlatform/google-cloud-iot-arduino/):

```
openssl ecparam -genkey -name prime256v1 -noout -out ec_private.pem
openssl ec -in ec_private.pem -pubout -out ec_public.pem
```

For the CA root, you should use:

```
wget pki.goog/roots.pem
openssl x509 -outform der -in roots.pem -out ca.crt
```
