### ISSUE TITLE
Support 2.5.x version of ESP8266 Library

### ISSUE THREAD

**Issue by gguuss** [GoogleCloudPlatform/google-cloud-iot-arduino#112]
Currently, newer versions of the ESP8266 library (those past 2.4.2) are not working properly with Cloud IoT Core. There's a resolution to disable fingerprint verification but this is not desirable.

**Comment by raresserban** [comment]
I am having some issues with the library and I think it is because of this. Can you share how to disable fingerprint verification?I just want to setup a simple DIY thermostat at home that I can query from Google Home so I am not really concerned with security.

**Comment by gguuss** [comment]
If you use 2.4.2, it should not have the issue with certificate validation.

**Comment by gguuss** [comment]
This should be resolved with release 1.1.7. Closing :)
