### ISSUE TITLE
About the "Root Certificate" expiration ...

### ISSUE THREAD

**Issue by sam0910** [GoogleCloudPlatform/google-cloud-iot-arduino#114]
Greetings! and Thank you for all these help.
This is about the "Root Certificate" expiration.
I understand that I need over-the-air mechanism, but 
When does it expire usually? I mean the period of rotate or expire the certificates.
If it is expired, every device will be stopped until they update new certificate OTA.
I am concerning about that.

**Comment by gguuss** [comment]
The Root certificate should remain valid until 2036 unless it's invalidated.  You can see a list of [the available certificates here](https://pki.goog/) the GTS roots are the ones you should be using with mqtt.googleapis.com - there is also [the LTS domain and certificates for Google Cloud IoT Core](https://cloud.google.com/iot/docs/how-tos/mqtt-bridge#using_a_long-term_mqtt_domain).
