### ISSUE TITLE
connection fails with mqtt->setUseLts(false);

### ISSUE THREAD

**Issue by stasysdr** [GoogleCloudPlatform/google-cloud-iot-arduino#124]
when mqtt->setUseLts(true); flag in row 182 in esp8266_mqtt.h is set to false (mqtt->setUseLts(**false**)), no connection can be established although "connect!" message is received at start.

**Comment by gguuss** [comment]
Thanks for reporting this, I'll take a look. What port are you using (8883 or 443)? Also, I believe that the root certificate may need to be different when you change the server.

**Comment by stasysdr** [comment]
tried both ports without success. used the same certificates as for tls though, which one would be correct?

**Comment by stasysdr** [comment]
The problem was the certificate. Connection worked with "GlobalSign Root CA - R2".
For some non LTS method is faster by about 2 seconds, which is very important when battery saving is priority.

**Comment by gguuss** [comment]
@stasysdr Thank you for reporting this!
