### ISSUE TITLE
Bug: CloudIoTCoreMqtt::mqttConnect ignores mqttClient's return code

### ISSUE THREAD

**Issue by matevarga** [GoogleCloudPlatform/google-cloud-iot-arduino#125]
https://github.com/GoogleCloudPlatform/google-cloud-iot-arduino/blob/f6a33d1c5af4148cc403482d295a6de5ab855022/src/CloudIoTCoreMqtt.cpp#L169

The underlying connect method can often return `false` without setting `_lastError` properly. In this case mqttConnect logs 'connected!', while in reality connection has failed.

**Comment by gguuss** [comment]
I've added a fix in the [log-fail-connect](https://github.com/GoogleCloudPlatform/google-cloud-iot-arduino/tree/log-fail-connect) branch.

**Comment by gguuss** [comment]
Added detection in [this pr](https://github.com/GoogleCloudPlatform/google-cloud-iot-arduino/pull/139), the condition is generally caused by an SSL issue.
