### ISSUE TITLE
ESP.getFreeHeap() gives free memory of 4~5kb on esp8266, give less room for adding more features.

### ISSUE THREAD

**Issue by khawajamechatronics** [GoogleCloudPlatform/google-cloud-iot-arduino#130]
Hi,

I am using Google IoT core in a project, and when I tried to add some more features related to project it start crashing.

Is there any way to optimize or get enough room?

**Comment by gguuss** [comment]
Good question! The short answer is to check through the "Tools" section within Arduino to increase available memory; for example, you could disable SPIFFS, disable the comprehensive SSL support, etc. 

The longer answer is that it depends on your board. You could buy an ESP8266 with more memory, I tend to use the WeMos D1 Mini, which includes 4MB of flash.
