### ISSUE TITLE
Gateway Example

### ISSUE THREAD

**Issue by zwells** [GoogleCloudPlatform/google-cloud-iot-arduino#135]
It would be amazing if this project had an example sketch like IBM IoT has:
https://github.com/ibm-watson-iot/device-arduino/blob/master/samples/ESP32BleGateway/ESP32BleGateway.ino

Example of a Bluetooth LE to Google IoT Gateway using ESP32/Arduino SDK

**Comment by gguuss** [comment]
Acknowledged!  If you want to contribute an example for the new complex section, I'd be happy to review it!

**Comment by galz10** [comment]
@zwells if you're still interested in the gateway example you can find it here

https://github.com/GoogleCloudPlatform/google-cloud-iot-arduino/tree/master/examples/complex/esp32/Gateway

**Comment by zwells** [comment]
Excellent! Thank You so much!
