### ISSUE TITLE
error

### ISSUE THREAD

**Issue by nzoffgrid** [GoogleCloudPlatform/google-cloud-iot-arduino#155]
C:\Users\gumbo\Documents\Arduino\libraries\google-cloud-iot-arduino-master\src\CloudIoTCoreMqtt.cpp: In member function 'void CloudIoTCoreMqtt::mqttConnect(bool)':

C:\Users\gumbo\Documents\Arduino\libraries\google-cloud-iot-arduino-master\src\CloudIoTCoreMqtt.cpp:48:18: error: '_backoff_at_millis' was not declared in this scope

   if (millis() < _backoff_at_millis)

                  ^

C:\Users\gumbo\Documents\Arduino\libraries\google-cloud-iot-arduino-master\src\CloudIoTCoreMqtt.cpp:80:7: error: '_backoff_at_millis' was not declared in this scope

       _backoff_at_millis = millis() + this->__backoff__;

       ^

C:\Users\gumbo\Documents\Arduino\libraries\google-cloud-iot-arduino-master\src\CloudIoTCoreMqtt.cpp:91:9: error: '_backoff_at_millis' was not declared in this scope

         _backoff_at_millis = millis() + __max_backoff__;

         ^

exit status 1
Error compiling for board LOLIN(WEMOS) D1 R2 & mini.

**Comment by DanielGarc** [comment]
see #154
