### ISSUE TITLE
will this work on the ESP32-CAM (camera_model_ai_thinker) ? 

### ISSUE THREAD

**Issue by otakexplode** [GoogleCloudPlatform/google-cloud-iot-arduino#162]

**Comment by galz10** [comment]
Hi can you provide a description describing your question

**Comment by gguuss** [comment]
This will work with the ESP32 cam (AI Thinker) but you may need to customize the configuration for the pins based on your specific model. The [existing configurations are all in separate `#define` blocks](https://github.com/GoogleCloudPlatform/google-cloud-iot-arduino/blob/master/examples/complex/esp32/camera/camera.ino#L85-L102). You generally should be able to determine these based on [the data sheet for your board](https://loboris.eu/ESP32/ESP32-CAM%20Product%20Specification.pdf).
