### ISSUE TITLE
Create topic using MAC Address (ESP8266)

### ISSUE THREAD

**Issue by ajlop** [GoogleCloudPlatform/google-cloud-iot-arduino#184]
Hi! I want to use the MAC address of the devices to create individuals topic of each one.
I am migrating my mqtt broker to google cloud and this is how I had it implemented (each new device created its own topic using its MAC address). can i use that architecture in google cloud? How can I implement it in GCP?

Thanks for your help !!

**Comment by gguuss** [comment]
You would need to use a service account to automatically add the device to the registry that you will be using for your data. This can be done using Cloud Functions, DataFlow, or other cloud compute-engine focused solutions. This is not a core part of IoT at present.

**Comment by gguuss** [comment]
Closing as this is out of scope for this project but marking as enhancement to inform the product team.
