### ISSUE TITLE
ESP32 subfolders

### ISSUE THREAD

**Issue by mars000** [GoogleCloudPlatform/google-cloud-iot-arduino#185]
Do you have an example of how I can publish and subscribe to a specific topic and subtopic.
its not clear from your existing examples how i can do this.

**Comment by galz10** [comment]
Hey mars, check out this link [Wiki Link](https://github.com/GoogleCloudPlatform/google-cloud-iot-arduino/wiki/How-to-push-to-a-specific-topic%3F) it might help with what you're looking for.

**Comment by mars000** [comment]
Thanks.

Any idea of how do I subscribe to a specific topic from say ESP32 device ?
