### ISSUE TITLE
Error: Header Includes not found

### ISSUE THREAD

**Issue by praveeno** [GoogleCloudPlatform/google-cloud-iot-arduino#19]
Hello, this may be a silly question, but I'm newbie in iot.
Recently I try to upload `esp8266-http` example in `node mcu ESP8266MOD`, 
and it give error
![image](https://user-images.githubusercontent.com/19618730/39662771-ba4e43f4-5084-11e8-9f24-d0d351087240.png)

where can i get this rBase64 header file

**Comment by gguuss** [comment]
Install the rBase64 library for Arduino.

**Comment by praveeno** [comment]
Yaa, Now It gives another library not found issue,
> String.h not found
and i'm not able to find any relevant library

**Comment by praveeno** [comment]
I convert 
> String.h  --> string.h

an it works fine.

**Comment by praveeno** [comment]
[continue the discussion on String vs string](https://github.com/GoogleCloudPlatform/google-cloud-iot-arduino/issues/21)
