### ISSUE TITLE
How to handle message published to topic?

### ISSUE THREAD

**Issue by mkroszka** [GoogleCloudPlatform/google-cloud-iot-arduino#198]
If I update config or send command to device arduino use messageReceived callback, but if I send message to topic  arduino not responding.

**Comment by amarkevich** [comment]
Google IoT support configuration [1] and command [2] topics only. To split commands by custom logic use {subfolder}.

1. https://cloud.google.com/iot/docs/how-tos/config/configuring-devices
2. https://cloud.google.com/iot/docs/how-tos/commands

**Comment by gguuss** [comment]
Closing, this is working as intended. Thank you @amarkevich for your help in answering this!
