### ISSUE TITLE
error: 'NN_DIGIT' does not name a type

### ISSUE THREAD

**Issue by praveeno** [GoogleCloudPlatform/google-cloud-iot-arduino#20]
when i try to compile example [`Esp32 mqtt`](https://github.com/GoogleCloudPlatform/google-cloud-iot-arduino/blob/dcc9b5eff0988dfe00616f9b0eacab94c1927189/examples/Esp32-mqtt/Esp32-mqtt.ino#L26), it gives error
> error: 'NN_DIGIT' does not name a type

**Comment by gguuss** [comment]
Which version of the library did you install? The latest stable / published release in the library manager should not have this issue.

**Comment by praveeno** [comment]
I've latest stable one.

**Comment by gguuss** [comment]
Thank you for the comment, I'm tracking another issue that is related -- I'm happy to [continue the discussion on String vs string]( https://github.com/GoogleCloudPlatform/google-cloud-iot-arduino/issues/21) in that thread if this is an issue that's hanging people up.
