### ISSUE TITLE
Connection not stable.

### ISSUE THREAD

**Issue by josemtrg** [GoogleCloudPlatform/google-cloud-iot-arduino#208]
Im trying to implement the given example for a NodeMCU using this example:

https://github.com/GoogleCloudPlatform/google-cloud-iot-arduino/tree/master/examples/Esp8266-lwmqtt

Everything seems to work but the problem is that the connection is not stable. It connect and disconnects right after a few seconds. This is the logs i get:

///////////////////////////////
Connecting to WiFi
Waiting on time sync...
Connecting...
Refreshing JWT
connected

Library connected!
0
 Connecting...
Refreshing JWT
connected

Library connected!
0
 Connecting...
Refreshing JWT
connected
////////////////////////////////

It seems that the problem is on the mqtt loop function

```
  if (!mqtt->loop())
  {
    mqtt->mqttConnect();
  }
```
On Google Core IoT i get the following logs:

<img width="887" alt="Screenshot 2020-11-09 at 11 28 56" src="https://user-images.githubusercontent.com/42574448/98535879-c4541300-227e-11eb-9775-4d1e85efcdeb.png">

When i try so send a command to the device i get an error message saying that the device is offline...

**Comment by gguuss** [comment]
Did you make any changes to the example? If you use the MQTT protocol in a way the bridge does not expect, ex. publish to the wrong topic, the protocol bridge will disconnect you.

**Comment by josemtrg** [comment]
@gguuss Thanks. That was it. I was missing the "events" topic.
