### ISSUE TITLE
i can't use the return of configuration sent to esp8266, mqtt.

### ISSUE THREAD

**Issue by Adryan-KS** [GoogleCloudPlatform/google-cloud-iot-arduino#209]
How can I handle the configuration message received from the iot core for esp8266. I can see on the serial monitor, but I can't find in the library how to handle this configuration message.

Serial Monitor:

Waiting on time sync...

Connecting...
Refreshing JWT
connected

Library connected!
incoming: /devices/xp5939303130350c0d17/config - na
incoming: /devices/xp5939303130350c0d17/config - config1
incoming: /devices/xp5939303130350c0d17/config - config2
incoming: /devices/xp5939303130350c0d17/config - config3

**Comment by gguuss** [comment]
It's [the callback function specified in esp8266_mqtt.h].
