### ISSUE TITLE
where i find primary_ca and backup_ca ? please help me, i use universal-lwmqtt example

### ISSUE THREAD

**Issue by Trion** [GoogleCloudPlatform/google-cloud-iot-arduino#216]
how i add primary_ca and backup_ca?

**Comment by gguuss** [comment]
It depends on your board but in general, these are stored in [ciotc_config.h](https://github.com/GoogleCloudPlatform/google-cloud-iot-arduino/blob/master/examples/universal-lwmqtt/ciotc_config.h) unless you are using the MKR-1000 board in which case the CA is set using the firmware updater.  Some [notes are in the documentation](https://github.com/GoogleCloudPlatform/google-cloud-iot-arduino#notes-on-the-certificate), please reopen if you see an error.

**Comment by Trion** [comment]
thanks
