### ISSUE TITLE
ESP8266_HTTP example not working.

### ISSUE THREAD

**Issue by pacifickashyap** [GoogleCloudPlatform/google-cloud-iot-arduino#26]
Refreshing JWT

 ets Jan  8 2013,rst cause:4, boot mode:(3,7)

wdt reset

**Comment by Vishalkpatu** [comment]
Same Here.
---------------------
Connecting to WiFi
Waiting on time sync...
Refreshing JWT
Abort called

ctx: sys 
sp: 3ffef850 end: 3fffffb0 offset: 01a0


ets Jan  8 2013,rst cause:4, boot mode:(3,2)

wdt reset
load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v4ceabea9
~ld

**Comment by gguuss** [comment]
Very interesting -- have you tried using [this diagnostic guide](http://arduino-esp8266.readthedocs.io/en/latest/faq/a02-my-esp-crashes.html) and the [ESP8266 exception decoder](https://github.com/me-no-dev/EspExceptionDecoder) to get a better idea where the watchdog timeout is happening?  

Sometimes it is helpful to switch to 160mhz on your board settings and updating your ESP8266 library to the latest to fix this kind of issue.

**Comment by gguuss** [comment]
Also make sure you've updated to the latest version of the ESP8266 SDK for Arduino.

**Comment by pacifickashyap** [comment]
Thanks @gguuss for your resonse. I have updated the ESp8266 SDK and now it's working.
I have watched your videos #GDDEurope, #GDDIndia. Big Fan!! :)
