### ISSUE TITLE
hi..I want to know is it possible to store data in firebase and have the sub / pub in the same function using the iot core in google cloud? any suggestion?

### ISSUE THREAD

**Issue by hanadjerbi1** [GoogleCloudPlatform/google-cloud-iot-arduino#37]

**Comment by hanadjerbi1** [comment]
okay...my first question
-how you make a connection between google cloud and firebase?

**Comment by hanadjerbi1** [comment]
okay...my first question
-how did you make the connection between google cloud and firebase?

**Comment by hanadjerbi1** [comment]
where i could run this command"npm install -g firebase-tools" with cmd ?

**Comment by gguuss** [comment]
@hanadjerbi1 I'm going to close this issue as Firebase integrations are external to this project.
