### ISSUE TITLE
WiFi and pubsub instances  

### ISSUE THREAD

**Issue by Gior80** [GoogleCloudPlatform/google-cloud-iot-arduino#41]
Actually WiFi and pubsub instances are declared inside the class, privately  . For the project i’m making I need to create those instances outside in my setup() and access it . So , could WiFi and pubsub be passed as parameter whe  I create the device object in my code ?

**Comment by gguuss** [comment]
This makes complete sense, we should [move the client instantiation out of CloudIoTCoreMQTTClient.h](https://github.com/GoogleCloudPlatform/google-cloud-iot-arduino/blob/master/src/CloudIoTCoreMQTTClient.h#L50).
