### ISSUE TITLE
How to publishTelemetry/State with MKR1000?

### ISSUE THREAD

**Issue by Razzo1987** [GoogleCloudPlatform/google-cloud-iot-arduino#42]
Hi,
I have seen the examples/Basic-MKR1000/ but there isn't any publish data.
I have tried to use the CloudIoTCoreMQTTClient on MKR1000 but the class use WiFiClientSecure and the code doesn't compile.

Someone have an example to publishTelemetry/State with MKR1000?

thanks

**Comment by gguuss** [comment]
@Razzo1987 Did you install the root certificate as described [here](https://www.hackster.io/arichetta/add-ssl-certificates-to-mkr1000-93c89d)?  Also, are you seeing the configuration messages?

**Comment by gguuss** [comment]
Closing issue, this is now supported in the lwMQTT examples.

**Comment by ripilot** [comment]
Hi all, whats the significance of 1510644967 in the code above?

**Comment by gguuss** [comment]
If you convert seconds since epoch of 1510644967, it's a date around November of 2017, roughly the first time of publish for the sample.  I believe you could use any value greater than zero, but I just wanted to make sure the current time stamp coming from the WiFi library was valid and recent.

**Comment by ajmalvb78** [comment]
hii all, 
iam sending data to a gcp cloud function successfully from my aurdino mkr wifi 1010 , but when my friend tries from another location( netherland ) he was not able to connect to iot core.my location was india . he and i was sending the data to same device , and using the same program , same private key, and added certicate for "mqtt.googleapis.com" on both of the aurdino mkr devices, does someone have any idea about the changes needed?
thanks in advance

**Comment by raphael-bmec-co** [comment]
Are you trying to do this at the same time? Google IoT core will only accept one connection from a device at a time. And if the connection is not closed or has not timed out then it will not accept a new connection. Try making a different device with it's own key pair.
