### ISSUE TITLE
Basic MKR Appears to Fail at Fill Private Key

### ISSUE THREAD

**Issue by sammodt** [GoogleCloudPlatform/google-cloud-iot-arduino#44]
Hi, thanks so much for all your work on this.

Advanced apologies as the following is most likely due to my lack of understanding rather than anything being wrong with the code - I'm new to Arduino...

I'm trying to run the Basic MKR example - it seems to run as far as Refreshing JWT and returning a string but then jumps over to printing time and LED OFF. My IoT Core console doesn't seem to be registering the connection as under last seen it's showing -- so I assume somethings going wrong in the fill private key section and it's eventually timing out and jumping on to the next bit of code?

Here's what my serial reads:

Connecting to WiFi
14:11:02.445 -> Waiting on time sync...
Connecting to: cloudiotdevice.googleapis.com
Getting jwt.
14:11:03.477 -> Refreshing JWT
eyJhbGciO......

14:11:12.114 -> 
14:11:12.114 -> LED OFF

14:11:16.110 -> 
14:11:16.110 -> LED OFF

14:11:20.159 -> 
14:11:20.159 -> LED OFF

Any pointers would be greatly appreciated,

Many thanks, 

Sam

**Comment by gguuss** [comment]
Try setting the configuration of the device to 1 from the Google Cloud console. The LED should turn on. Next, set the configuration of the device to 0 from the Google Cloud console. the LED should turn off.

**Comment by gguuss** [comment]
It actually looks like the example is working for you, just need to change the configuration in the console.
