### ISSUE TITLE
ESP8266 MQTT - Callback function is null - Causes crash (https://github.com/GoogleCloudPlatform/google-cloud-iot-arduino/tree/master/examples/Esp8266-http) is the only supported version. I  I have been working on porting MQTT to work for the 8266 but there's some strange issue that causes crashes.

### ISSUE THREAD

**Issue by manojvellala** [GoogleCloudPlatform/google-cloud-iot-arduino#50]
_Originally posted by @gguuss in https://github.com/GoogleCloudPlatform/google-cloud-iot-arduino/issues/27#issuecomment-403162615_

Mqtt crashes  at multiple points. The callback function pointer is found to be Null and crashes. I suspect memory over write or mishandling of the call back pointer.

**Comment by gguuss** [comment]
Should be resolved by [this PR](https://github.com/GoogleCloudPlatform/google-cloud-iot-arduino/pull/54).

**Comment by gguuss** [comment]
Reopening, MQTT is not yet implemented for 8266

**Comment by gguuss** [comment]
Closing again as this is already tracked in a separate issue.
