### ISSUE TITLE
publishTelemetry with binary data

### ISSUE THREAD

**Issue by alexodus** [GoogleCloudPlatform/google-cloud-iot-arduino#64]
Please support publishTelemetry with binary data (aka const uint8_t* payload, unsigned int plength, like PubSub library)

**Comment by gguuss** [comment]
What happens when you Base64 encode the data? Is this specific to the lwMQTT examples?

**Comment by alexodus** [comment]
I want to send a large amount of data and I want stay under the 1024 byte limit. Base64 is not ok.

**Comment by gguuss** [comment]
Got it, makes total sense.  Would it be helpful to add another MQTT example that shows this? (I've been trying to come up with an excuse to learn i2s with the esp32.

**Comment by gguuss** [comment]
An update here, in the existing samples you have access to the raw MQTT device, which can accept a byte array:

```c++
  if (millis() - lastMillis > 60000) {
    lastMillis = millis();
    mqttClient->publish("/devices/arduino-taste/events", data, 255);
  }
```

It could make sense to expose this as a helper.

**Comment by gguuss** [comment]
This has been added in the release v1.1.5.
