### ISSUE TITLE
 API support for multiple topics

### ISSUE THREAD

**Issue by alexodus** [GoogleCloudPlatform/google-cloud-iot-arduino#65]
Since February 21, 2018 (https://cloud.google.com/iot/docs/release-notes) "device registries can now have multiple associated Cloud Pub/Sub topics". Your API support only one topic. I'm in wrong?

https://cloud.google.com/iot/docs/how-tos/devices#creating_a_device_registry_with_multiple_pubsub_topics

**Comment by gguuss** [comment]
You could tailor the lwMQTT samples to publish to multiple topics pretty easily. The CloudIoTMQTTDevice wrapper on the other hand... probably could use a refactor.

**Comment by Gior80** [comment]
@gguuss does lwmqtt implements jwt renewal ?

**Comment by gguuss** [comment]
I tested it on the ESP8266 and when the client reconnects a new JWT and connection credential are created.  I'm not 100% sure the device didn't reset and have not closely assessed the refresh flow.

**Comment by gguuss** [comment]
JWT refresh should happen in [getJWT](https://github.com/GoogleCloudPlatform/google-cloud-iot-arduino/blob/master/examples/Esp32-lwmqtt/esp32-mqtt.h#L44-L52) when [it's called by mqttConnect](https://github.com/GoogleCloudPlatform/google-cloud-iot-arduino/blob/master/examples/Esp32-lwmqtt/esp32-mqtt.h#L96-L99).

**Comment by gguuss** [comment]
I believe all of this functionality should be encapsulated in CloudIoTMQTTJwt but I want to get the examples with lwMQTT into a good state and then have a major version bump and fully migrate to PlatformIO before trying to do this.

**Comment by Gior80** [comment]
yep , that would be great have this parameter ( Jwt expires ). included into the object creation ,  if can help let me know ! 

Giorgio

**Comment by gguuss** [comment]
As MQTTDevice has been refactored, it could make sense to move this to `ciotc_config.h` as well and just configure with an array of topics. We should also add the option for commands and gateway topics.

**Comment by gguuss** [comment]
An update, release 1.1.3 will have support for subfolders when publishing telemetry.

**Comment by gguuss** [comment]
@Gior80 JWT refresh should now work, closing this issue as I added support for publishing to separate subfolders in the 1.1.3 release.

Next I'll be making one unified sample that supports all hardware from a single example.
