### ISSUE TITLE
Confirm configuration 

### ISSUE THREAD

**Issue by Gior80** [GoogleCloudPlatform/google-cloud-iot-arduino#69]
Hi :) 

Testing the flow of configuration everything work ok . I’m able to send config to device via console or nodejs cloud function without problem . 

Data arrive to the device , I do stuffs (ex power up the led ) and so on 

Only point Is that I probably not understand how the device acknowledge the conf .  Looking at registry console in fact looks like configuration is never confirmed from device .

Do I need to send back special ack message ? 

https://ibb.co/Gd4bX8d

Also would add an esp32 specific problem resolution. Seems that power management on esp32 WiFi make the connection lag like hell and generating ex hearbeat problem over long period. Setting :

WiFi.setSleep(false)

Before WiFi begin would improve so much the reliability and speed of connection . This unfortunately happen on esp32 only , esp2866 is not affected

**Comment by gguuss** [comment]
Added [in this branch](https://github.com/GoogleCloudPlatform/google-cloud-iot-arduino/tree/setsleep).

**Comment by Gior80** [comment]
Me too , that’s why I moved to lwmqtt in past . Btw i couldn’t successfully renew the jwt token by disconnect and reconnect client . Always get the infamous -5 error in my code. Have u been successful on that ? This is absolutely necessary for long time run of client

**Comment by gguuss** [comment]
For PubSub, the advanced sample explicitly destroys and recreates the objects in memory for reconnect, which did work in my testing. For lwMQTT, I have not yet thoroughly tested JWT renewal. For the HTTP example, the JWT is checked before each request and is refreshed when it expires.

**Comment by Gior80** [comment]
Pubsub work , with lwmqtt seems not , but I have not destroyed object in memory . Just disconnect , recreate jwt and reconnect . Have u plan for test it too ? I can also provide starting code

**Comment by marcelvanheist** [comment]
Regarding the acknowledgment of the config message; make sure you subscribe to the config topic with QoS set to 1 like so: `mqttClient->subscribe(device->getConfigTopic(), 1);`. Then the config messages will be acknowledged.

**Comment by gguuss** [comment]
I'll update the samples.

**Comment by gguuss** [comment]
I've [added the QoS settings in this PR](https://github.com/GoogleCloudPlatform/google-cloud-iot-arduino/commit/14f7e3124b696545a1090a9b3a0b7bf0c48a945d), I mistakenly added then removed the sleep call in ESP8266 then encountered issues with Esp32, I'll see about adding it back.

**Comment by gguuss** [comment]
This should be resolved in release 1.1.2
