### ISSUE TITLE
Exception after running code for >5mins

### ISSUE THREAD

**Issue by yashkar** [GoogleCloudPlatform/google-cloud-iot-arduino#77]
I am able to successfully communicate with the HTTP example. However, after running the code for about 5mins or so, I get an exception. Any idea why?

Exception (29):
epc1=0x402155d6 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000004 depc=0x00000000
ctx: cont 
sp: 3fff0d70 end: 3fff1290 offset: 01a0

**Comment by gguuss** [comment]
What version of the ESP8266 library are you using?

**Comment by gguuss** [comment]
The exception data is not very useful without translating the instructions / etc with a tool like [ESP Exception Decoder](https://github.com/me-no-dev/EspExceptionDecoder). Maybe install the debugger and then see if that helps.

**Comment by gguuss** [comment]
Also, it's very strange that you're encountering the issue after a duration... Can you also share the following:

* Board you're using
* Board support package version (e.g. ESP8266 by Esp Community, version 2.5.0-beta3)
* Example you are using

**Comment by gguuss** [comment]
There have been odd issues recently with certain ESP developer boards, I'll see if I can find out more information. This could be due to the different memory configurations of the boards. Also, closing the issue as we'll be focusing on MQTT for now.
