### ISSUE TITLE
keepalive/heartbeat on google iot core

### ISSUE THREAD

**Issue by alexodus** [GoogleCloudPlatform/google-cloud-iot-arduino#88]
In google cloud IoT Core the heartbeats (PINGREQ) are billed.
In my test (see the screenshot) with this librari I've 8 heartbeats/minute!!!

![image](https://user-images.githubusercontent.com/2721510/53326418-d5f85a00-38e5-11e9-9336-63e3ec896385.png)

I tested with 60seconds (the default is 10 seconds) but the results are the same: 8 heartbeats/minute!!!
How to reduce these useless heartbeats?

**Comment by alexodus** [comment]
this screen is about stackdriver on a single device:
![image](https://user-images.githubusercontent.com/2721510/53337016-69d71f80-3900-11e9-8f6b-b5579c56246e.png)

**Comment by gguuss** [comment]
Thanks for the report, confirming I'm seeing the issue and will see if I can figure out a way to disable.

**Comment by gguuss** [comment]
The changes in this commit [explicitly increase the keepAlive / heartbeat](https://github.com/GoogleCloudPlatform/google-cloud-iot-arduino/commit/44fd3068080e4f7300acc0dc4ae27d92b8d5c181) and will be in the next library release.

**Comment by gguuss** [comment]
Which sample are you running?

**Comment by gguuss** [comment]
Changes released in version 1.1.2, that said, I'm not seeing the heartbeat messages being generated by default.
